name: Deploy v3 Vault Subgraphs
on:
  push:
    branches: main
    paths:
      - "subgraphs/v3-vault/**"
jobs:
  deploy-mainnet:
    uses: ./.github/workflows/deploy-subgraph.yml
    with:
      working-directory: subgraphs/v3-vault
      subgraph-name: balancer-v3
      manifest-file: subgraph.yaml
    secrets:
      GRAPH_DEPLOY_KEY: ${{ secrets.GRAPH_DEPLOY_KEY }}
  
  deploy-gnosis:
    uses: ./.github/workflows/deploy-subgraph.yml
    with:
      working-directory: subgraphs/v3-vault
      subgraph-name: balancer-v3-gnosis
      manifest-file: subgraph.gnosis.yaml
    secrets:
      GRAPH_DEPLOY_KEY: ${{ secrets.GRAPH_DEPLOY_KEY }}

  deploy-sepolia:
    uses: ./.github/workflows/deploy-subgraph.yml
    with:
      working-directory: subgraphs/v3-vault
      subgraph-name: balancer-v3-sepolia
      manifest-file: subgraph.sepolia.yaml
    secrets:
      GRAPH_DEPLOY_KEY: ${{ secrets.GRAPH_DEPLOY_KEY }}
