name: Deploy Graph Studio Prod

on:
  push:
    branches: main

jobs:
  deploy-studio-sepolia:
    runs-on: ubuntu-latest
    environment: graph
    defaults:
      run:
        working-directory: ./subgraphs/vault
    steps:
      - uses: actions/checkout@v3
      - name: Install node
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install
        run: yarn install
      - name: Codegen
        run: yarn codegen
      - name: Build
        run: yarn build
      - uses: balancer-labs/graph-deploy@v0.0.1
        with:
          graph_deploy_key: ${{secrets.GRAPH_DEPLOY_KEY}}
          graph_version_label: ${GITHUB_SHA::8}
          graph_subgraph_name: "balancer-sepolia-v3"
          graph_account: "balancer-labs"
          graph_config_file: "subgraph.yaml"
          graph_deploy_studio: true
