# name: Deploy Graph Studio Prod
# on:
#   push:
#     branches: main

# jobs:
#   deploy-pools-sepolia:
#     runs-on: ubuntu-latest
#     environment: graph
#     steps:
#       - uses: actions/checkout@v3
#       - name: Install node
#         uses: actions/setup-node@v3
#         with:
#           node-version: 18
#       - name: Install pnpm
#         uses: pnpm/action-setup@v2
#         with:
#           version: 8
#       - name: Install dependencies
#         run: pnpm install
#       - name: Generate manifests
#         run: pnpm generate-manifests
#       - name: Graph Codegen
#         working-directory: subgraphs/pools
#         run: pnpm codegen subgraph.sepolia.yaml
#       - name: Graph Build
#         working-directory: subgraphs/pools
#         run: pnpm build subgraph.sepolia.yaml
#       - uses: balancer-labs/graph-deploy@v0.0.1
#         with:
#           graph_deploy_key: ${{secrets.GRAPH_DEPLOY_KEY}}
#           graph_version_label: ${GITHUB_SHA::8}
#           graph_subgraph_name: "balancer-pools-v3-sepolia-7th"
#           graph_account: "mendesfabio"
#           graph_config_file: "subgraphs/pools/subgraph.sepolia.yaml"
#           graph_deploy_studio: true

#   deploy-vault-sepolia:
#     runs-on: ubuntu-latest
#     environment: graph
#     steps:
#       - uses: actions/checkout@v3
#       - name: Install node
#         uses: actions/setup-node@v3
#         with:
#           node-version: 18
#       - name: Install pnpm
#         uses: pnpm/action-setup@v2
#         with:
#           version: 8
#       - name: Install dependencies
#         run: pnpm install
#       - name: Generate manifests
#         run: pnpm generate-manifests
#       - name: Graph Codegen
#         working-directory: subgraphs/vault
#         run: pnpm codegen subgraph.sepolia.yaml
#       - name: Graph Build
#         working-directory: subgraphs/vault
#         run: pnpm build subgraph.sepolia.yaml
#       - uses: balancer-labs/graph-deploy@v0.0.1
#         with:
#           graph_deploy_key: ${{secrets.GRAPH_DEPLOY_KEY}}
#           graph_version_label: ${GITHUB_SHA::8}
#           graph_subgraph_name: "balancer-v3-sepolia-7th"
#           graph_account: "mendesfabio"
#           graph_config_file: "subgraphs/vault/subgraph.sepolia.yaml"
#           graph_deploy_studio: true
